# .NET Core
# Build and test .NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  name: Azure Pipelines
  vmimage: windows-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.sln'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*.sln'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'

# You can build a platform based executeable with the following task instead of the above one
# Make sure you set the right platform with the -r parameter
#- task: DotNetCoreCLI@2
#  inputs:
#    command: 'publish'
#    publishWebProjects: false
#    projects: '**/Battleship.Ascii.csproj'
#    arguments: '--configuration $(BuildConfiguration) -r win-x64 --output $(build.artifactstagingdirectory)'
#    zipAfterPublish: false

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: |
      **/*[Tt]ests/*.csproj
      **/*ATDD/*.csproj
    arguments: '--configuration $(BuildConfiguration) --collect "Code Coverage"'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
  condition: succeededOrFailed()
